### PR TITLE
reexport MosaicViews

### PR DESCRIPTION
**Pull request by johnnychen94**
~Don't merge this until https://github.com/JuliaArrays/MosaicViews.jl/pull/14 get merged, I will rebuild the test when MosaicViews v0.2.0 is registered.~

TODO:
- [x] tests are needed because MosaicViews isn't under JuliaImages :P

I bumped a minor version because from now on this package isn't invisible to users anymore. After this, I'll also reexport `ImageShow` from `Images`, and then draft a democard in [juliaimages.org](https://juliaimages.org/latest/democards/examples/)

Another choice is to reexport it in `ImageCore` because `ImageCore` is a collection of different views.

---

`MosaicViews` provides a handy tool `mosaicview`, which can be seen as an enhanced version of `cat` to make visualization easier. Here're two main usages:

1. Compare images of different sizes and colorants (not necessarily two images)

```julia
using ImageShow, TestImages
using ColorVectorSpaces # for zero(RGB{N0f8})

lena = testimage("lena") # 256*256 RGB image
cameraman = testimage("cameraman") # 512*512 Gray image
mosaicview(lena, cameraman; nrow=1)
```

image

2. give a nice looking 2d view for higher-dimensional image (or images)

```julia
using ImageShow, TestImages
img = testimage("mri") # 226×186×27

mosaicview(img; fillvalue=0.5, npad=2, ncol=7, rowmajor=true)
```

image

### CODE REVIEW

**Comment by johnnychen94** [comment]
Since MosaicView depends on OffsetArrays, I think it's ok to revert #17. With OffsetArray 1.0 released, the main motivation of that is "outdated" now.

**Comment by RalphAS** [comment]
Looks fine so far.  Do you have a design for a test?

**Comment by johnnychen94** [comment]
> Do you have a design for a test?

ReferenceTests are designed for such usages 😄  -- the 22 reference images occupy 88K storage, which is small enough to manage with git.

**Comment by johnnychen94** [comment]
The test failures are because ColorVectorSpace isn't compatible with ColorTypes v0.10

https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/128

**Comment by johnnychen94** [comment]
@timholy do you think it's appropriate to move this PR to ImageCore?

**Pull request closed without merging**
