### PR TITLE
add `gif` function

### PR DESCRIPTION
**Pull request by johnnychen94**
Originally proposed in https://github.com/JuliaImages/ImageShow.jl/issues/22#issuecomment-616759613. This is a simple and yet powerful alternative to #29 for 3d image.

Example:

```julia
using ImageShow, TestImages, ImageTransformations

# 3d image
ImageShow.gif(testimage("mri-stack"))

# 2d images
toucan = testimage("toucan") # 150×162 RGBA image
moon = testimage("moon") # 256×256 Gray image
ImageShow.gif([toucan, moon])

# a do-function version
img = testimage("cameraman")
ImageShow.gif(-π/4:π/16:π/4]; fps=3) do θ
    imrotate(img, θ, axes(img))
end
```

- [x] requires https://github.com/JuliaIO/ImageMagick.jl/pull/199 (ImageMagick >= v1.2.0)
- [x] need test

### CODE REVIEW

**Comment by timholy** [comment]
What do you see as the main benefit/different in the function-call vs macro form?

**Comment by johnnychen94** [comment]
No actual difference; I thought making it a macro is a kind of visual sign to indicate users that this is only for "interactive" usage.

**Comment by ashwani-rathee** [comment]
@johnnychen94 Is it possible as of now to show gif properly in ImageInTerminal.jl . Last I tried,it showed the gif as array of images one after another in column..

**Comment by johnnychen94** [comment]
ImageInTerminal does not understand GIF encoding, so I don't think it's possible as of now. https://github.com/JuliaImages/ImageInTerminal.jl/issues/45 could possibly support it.

This PR is not released yet, I'm working on #29 now.

**Pull request merged**
